import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import Layout from "../components/layout";

const Home: NextPage = () => {
    const { data: secretMessage } = trpc.auth.getAllPizzas.useQuery();

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                lol
                <div>{JSON.stringify(secretMessage)}</div>
            </Layout>
        </>
    );
};

export default Home;
