import type { NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import Layout from "../components/layout";
import { useRouter } from "next/router";

const Home: NextPage = () => {
    const { data: authData } = useSession();
    const router = useRouter();

    return (
        <>
            <Head>
                <title>Pizzers | Home</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <div className="bg-base-200 p-10">
                    <h1 className="text-5xl font-bold">Welcome back {authData?.user?.name}!</h1>
                    <div className="flex gap-4">
                        <button className="btn-primary btn mt-5" onClick={() => router.push("/new")}>
                            New Order
                        </button>
                        <button className="btn-primary btn mt-5" onClick={() => router.push("/account/orders")}>
                            Previous Orders
                        </button>
                    </div>
                </div>
            </Layout>
        </>
    );
};

export default Home;
