import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Welcome to Timers. Here you can play games to learn your times tables</h1>
            <div className={"space-y-3"}>
                <div className="space-y-1 text-sm">
                    <h3 className="font-medium leading-none">Grid!</h3>
                    <p className="text-xs text-slate-500 dark:text-slate-400">Fill out the grid as fast as possible!</p>
                </div>
            </div>
        </>
    );
};

export default Home;
